### ISSUE TITLE
Allow to store multiple models

### ISSUE THREAD

**Issue by kucho** [julionav/lazyrecord#5]
Currently the store does not allow to persist several models because each class writes a 'lazy record.store' and it keeps getting overwritten.

**Comment by julionav** [comment]
Hey @kucho 

Could you provide more info about the issue you are having?

**Comment by julionav** [comment]
I just updated the tests to include one with multiple models and it seems to be working fine.

However, I did say that If I removed a model after one object of it has been persisted in `pstore` it throws an error.

Looks like this:
```
Failure/Error:
  @data.transaction do
    yield
  end

ArgumentError:
  undefined class/module Post
# ./lib/lazyrecord.rb:48:in `transaction'
# ./lib/lazyrecord.rb:7:in `initialize'
# ./lib/lazyrecord.rb:117:in `new'
# ./lib/lazyrecord.rb:117:in `store'
# ./lib/lazyrecord.rb:91:in `inherited'
```

**Comment by kucho** [comment]
> Hey @kucho
> 
> Could you provide more info about the issue you are having?



> I just updated the tests to include one with multiple models and it seems to be working fine.
> 
> However, I did say that If I removed a model after one object of it has been persisted in `pstore` it throws an error.
> 
> Looks like this:
> 
> ```
> Failure/Error:
>   @data.transaction do
>     yield
>   end
> 
> ArgumentError:
>   undefined class/module Post
> # ./lib/lazyrecord.rb:48:in `transaction'
> # ./lib/lazyrecord.rb:7:in `initialize'
> # ./lib/lazyrecord.rb:117:in `new'
> # ./lib/lazyrecord.rb:117:in `store'
> # ./lib/lazyrecord.rb:91:in `inherited'
> ```

The error occurs when we try to use the store for a second time after storing objects of different classes. 

When the first class inherits from LazyRecord it loads all the objects from persistence. However, by that time not all the clases stored were defined in the execution.

We need to defer opening the store until all the class definitions are ready.
